# Generated by Django 5.2.1 on 2025-06-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmoderation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
