# Generated by Django 4.2.16 on 2025-06-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='refund',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID de la transaction de remboursement', max_length=100, null=True),
        ),
    ]
