# Generated by Django 4.2.16 on 2025-06-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_refund_status_refund_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Raison du rejet, si applicable', null=True),
        ),
    ]
